on:
  push:
    branches:
      - main
      - master
      - release/*

jobs:
  test:
    name: Test on deno ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - run: git config --global core.autocrlf false

      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run Test
        run: |
          deno task test-cov

      - name: Run build
        run:  deno task build
      - uses: codecov/codecov-action@v3
        with:
          files: coverage/lcov.info
