on:
  push:
    branches:
      - main
      - master
      - release/*

jobs:
  test:
    name: Test on deno ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - run: git config --global core.autocrlf false

      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Run build
        run: deno task build

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
